server:
  port: 7003
  servlet:
    context-path: /api

spring:
  cloud:
    gateway:
      discovery:
        locator:
          enabled: false  #开启spring cloud gateway自动根据服务发现为每一个服务创建了一个router，这个router将以服务名开头的请求路径转发到对应的服务。
          lowerCaseServiceId: true   #是将请求路径上的服务名配置为小写（因为服务注册的时候，向注册中心注册时将服务名转成大写的了），比如以/service-hi/*的请求路径被路由转发到服务名为service-hi的服务上。
          filters:
          - StripPrefix=1
      routes:
      - id: num1
        uri: lb://boot-server
        predicates:
        - Path= /api/boot/**,/api/boot2/**
        #        - Host=**.foo.org
        #        - Path=/headers
        #        - Method=GET
        #        - Header=X-Request-Id, \d+
        #        - Query=foo, ba.
        #        - Query=baz
        #        - Cookie=chocolate, ch.p
        #        - After=2018-01-20T06:06:06+08:00[Asia/Shanghai]
        filters:
        #转发时去掉n层虚拟路径
        - StripPrefix=2
      - id: ums
        uri: lb://ums-server
        predicates:
        - Path= /api/ums/**
        #        - Host=**.foo.org
        #        - Path=/headers
        #        - Method=GET
        #        - Header=X-Request-Id, \d+
        #        - Query=foo, ba.
        #        - Query=baz
        #        - Cookie=chocolate, ch.p
        #        - After=2018-01-20T06:06:06+08:00[Asia/Shanghai]
        filters:
        - StripPrefix=2
